### ISSUE TITLE
Feature request: HD-quality?

### ISSUE THREAD

**Issue by ajan1** [rasjani/plugin.video.moontv.fi#1]
There is HD-quality on newest videos on MoonTV. Could this support it?

**Comment by ajan1** [comment]
I think at this is first HD-quality video
http://moontv.fi/ohjelmat/pelit/gamer/hyrule-warriors

**Comment by rasjani** [comment]
Into consideration

**Comment by rasjani** [comment]
Btw, since you have probably worked with MoonTV.fi website,  kuuraketti.fi has some tweaks that tries to prevent the usage of the videos via 3rd parties ..  i can work around those (and already have code to do so) but since i do rely on just scraping the web pages, getting the content to KODI/xbmc is at most times very painful.

I've asked multiple times to get official support where the content could be fetches without these sort of hazzles but so far i've never gotten a single reply - and thus, i have not been very active in maintaining the addon either ..

**Comment by ajan1** [comment]
I will send email to you.

**Comment by rasjani** [comment]
Thanks! 

Btw, i think my dev3 branch already supports hd vids .. but i'll keep this open until the code lands into master and i make a new release of addon.

**Comment by rasjani** [comment]
master branch is now updated with all the relevant fixes and plugin will always use the highest available. Closing this for now ..
